#define DM_ODM_SUPPORT_TYPE_CE 1
#undef DM_ODM_SUPPORT_TYPE_AP
#undef DM_ODM_SUPPORT_TYPE_WIN
#undef DM_ODM_SUPPORT_TYPE_ADSL
#undef DM_ODM_SUPPORT_TYPE_IOT

#undef DM_ODM_CE_MAC80211
#undef DM_ODM_CE_MAC80211_V2
