# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_RTL8XXXU_COPY)	+= rtl8xxxu_copy.o

rtl8xxxu_copy-y	:= rtl8xxxu_core.o rtl8xxxu_8192e.o rtl8xxxu_8723b.o \
		   rtl8xxxu_8723a.o rtl8xxxu_8192c.o rtl8xxxu_8822b.o
